all:	configure

configure:	 configure.in Makefile.am src/Makefile.am
	@aclocal
	@libtoolize --force --copy
	@autoheader
	@automake --add-missing --copy
	@autoconf

clean:
	@if [ -f Makefile ]; then make distclean; fi || true
	@rm -rvf *.cache *.log *.status *.m4
	@rm -rvf src/Makefile.in src/config.h.in src/config.h src/stamp-h.*
	@rm -rvf Makefile.in config.*
	@rm -rvf missing install-sh mkinstalldirs depcomp ltmain.sh
	@rm -rvf configure stamp-h.*
