.TH "LINUXSAMPLER" "1" 
.SH "NAME" 
linuxsampler \(em a realtime audio sampler 
.SH "SYNOPSIS" 
.PP 
\fBlinuxsampler\fR 
.SH "DESCRIPTION" 
.PP 
\fBlinuxsampler\fR LinuxSampler is a work in progress. It's goal is to produce a free 
software audio sampler with professional grade features. 
.PP 
It offers disk streaming capability and supports the Gigasampler format 
which is currently considered to be the best sampler format in regards of 
possibilities and sound quality. 
.PP 
This package provides the backend of LinuxSampler, that is the sampler 
engine together with audio and MIDI drivers. LinuxSampler can be 
controlled via network interface which uses an ASCII based protocol called 
LSCP. You might consider to install a GUI frontend for LinuxSampler as 
well. 
.PP 
For more informations please visit http://www.linuxsampler.org 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below.  For a complete description, see the 
\fBInfo\fP files. 
.IP "          \fB\-\-help\fP         " 10 
Show summary of options. 
.IP "          \fB\-\-version\fP         " 10 
Show version of program. 
.IP "          \fB\-\-profile\fP         " 10 
profile synthesis algorithms 
.IP "          \fB\-\-no-tune\fP         " 10 
disable assembly optimization 
.IP "          \fB\-\-statistics\fP         " 10 
prints periodically statistics 
.SH "AUTHOR" 
.PP 
This manual page was written by Matt Flax flatmax@ieee.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Tue 22 Mar 2005, 01:18 
