language: cpp

sudo: required
dist: trusty

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq

install:
- sudo apt-get install libqt4-dev liblscp-dev libgig-dev

before_script:
- ./autogen.sh

script:
- ./configure --enable-qt4
  && make
  && sudo make install
