debian/tmp/usr/include/* usr/include
debian/tmp/usr/lib/linuxsampler/include/* usr/lib/linuxsampler/include
debian/tmp/usr/lib/linuxsampler/lib*.a usr/lib/linuxsampler
debian/tmp/usr/lib/linuxsampler/lib*.la usr/lib/linuxsampler
debian/tmp/usr/lib/linuxsampler/lib*.so usr/lib/linuxsampler
debian/tmp/usr/lib/pkgconfig/linuxsampler.pc usr/lib/pkgconfig
debian/tmp/usr/share/aclocal/* usr/share/aclocal
doc/html/* usr/share/doc/liblinuxsampler-dev/html
